### PR TITLE
Update bundle task name in accordance with RN 0.71

### LINKED ISSUE #31: Issues building Android app with the latest RN 0.71
In the latest version of RN 0.71 the `build.gradle` has been changed a lot because of adopting New Architecture and introducing new  React Native Gradle Plugin. And now this package doesn't allow to build the Android app with the following error: 

```
FAILURE: Build failed with an exception.

* Where:
Script '/private/tmp/AwesomeProject/node_modules/react-native-vector-image/strip_svgs.gradle' line: 10

* What went wrong:
Cannot get property 'name' on null object

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Script '/private/tmp/AwesomeProject/node_modules/react-native-vector-image/strip_svgs.gradle' line: 10

* What went wrong:
Cannot get property 'name' on null object

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
```

### PR DESCRIPTION
**Pull request by sejongk**
Resolves #31 

- Updates the bundle task name that was previously used as `bundle${targetName}JsAndAssets` to `createBundle${targetName}JsAndAssets`.
- Adds the if statement that checks whether `bundleTask` is valid, because there is no `createBundleDebugJsAndAssets` in the debug mode.
- Removes `bundleTasks`, that seems defined and not used.

If there is anything I missed, please let me know.

Signed-off-by: Sejong Kim <sepaper@naver.com>

### CODE REVIEW

**Comment by WookieFPV** [comment]
This fixes my build issue on  RN 0.71.3 using the "old" Arch.

(new Arch is still blocked by #31 even with this fix)

**Comment by oblador** [comment]
Hi and thanks for your PR, this breaks backwards compatibility if I read it correctly. Could you update the PR to make it work with either task name? Thanks!

**Comment by krudos** [comment]
this PR will work after @klarna/react-native-vector-drawable is merge with https://github.com/klarna-incubator/react-native-vector-drawable/pull/10 that solves new arch error

**Comment by oblador** [comment]
This should now be fixed in 0.4.0 👍

**Pull request closed without merging**
